# Generated by Django 4.2.5 on 2023-10-02 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_app', '0002_portfolio_alter_student_major_student_portfolio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='about',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='contact_email',
            field=models.CharField(max_length=200),
        ),
    ]
