# Generated by Django 4.2.5 on 2023-10-20 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_app', '0006_delete_projectsinportfolio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='description',
        ),
        migrations.AddField(
            model_name='project',
            name='about',
            field=models.TextField(blank=True),
        ),
    ]
