# Generated by Django 4.2.5 on 2023-10-20 02:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_app', '0007_remove_project_description_project_about'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='about',
            new_name='description',
        ),
    ]
